package com.jayrave.falkon.sample_android

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import com.jayrave.falkon.sample_android.tables.MessagesTable
import com.jayrave.falkon.sample_android.tables.UsersTable

/**
 * A great way to manage the schema:
 * http://blog.danlew.net/2016/08/16/trello-android-schema-upgrades/
 */
class SampleSqliteOpenHelper(context: Context) :
        SQLiteOpenHelper(context, "falkon_sample_db", null, 1) {

    override fun onCreate(db: SQLiteDatabase) {
        try {
            db.beginTransaction()

            /**
             * These SQL were generated by [UsersTable] & [MessagesTable] via their
             * `buildCreateTableSql` API
             */

            db.execSQL("CREATE TABLE users (id TEXT, first_name TEXT(255), last_name TEXT(255), email_id TEXT, age INTEGER, photo_url TEXT, last_seen_at INTEGER, PRIMARY KEY (id), UNIQUE (photo_url));")
            db.execSQL("CREATE TABLE messages (id TEXT, content TEXT, sent_at INTEGER, received_at TEXT, from_user_id TEXT, to_user_id TEXT, PRIMARY KEY (id), FOREIGN KEY (from_user_id) REFERENCES users(id), FOREIGN KEY (to_user_id) REFERENCES users(id));")
            db.setTransactionSuccessful()
        } finally {
            db.endTransaction()
        }
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        // Do upgrade related stuff here
    }
}